import Script from 'next/script'
import './globals.css'

export const metadata = {
  title: 'Desakuw.',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='container mx-auto'>
      <body>
        {children}
        <Script src='./node_modules/flowbite/dist/flowbite.min.js' />
      </body>
    </html>
  )
}
